before_script:
  - mkdir -p ~/.ssh
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - ssh-keyscan -H 'www.mehla.in' >> ~/.ssh/known_hosts

stages:
  - deploy
  
deploy_to_dokku:
  stage: deploy
  script:
    - git push dokku@www.mehla.in:www master:master
