stages:
  - clean_up
  - build
  
build_and_deploy_prod:
  stage: build
  script:
    - npm install
    - git push dokku master
  only:
    - master

clean_up_job:
  stage: clean_up
  script:
    - rm -rf dist/